#!/usr/bin/env bash
# Write nginx reverse-proxy listeners on 8080 (Observability Kibana) and 8081 (Security Kibana)
# so the es3-api lab host backs two Instruqt service tabs. Run with sudo after .env is filled.

set -euo pipefail

ROOT="${ELASTIC_WORKSHOP_ROOT:-/root/elastic-workshop}"
ENV_FILE="${1:-$ROOT/.env}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/sites-available/elastic-lab-kibana-proxy.conf}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "Missing env file: $ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

if [ -z "${O11Y_KIBANA_URL:-}" ] || [ -z "${SECURITY_KIBANA_URL:-}" ]; then
  echo "Set O11Y_KIBANA_URL and SECURITY_KIBANA_URL in $ENV_FILE (HTTPS Kibana base URLs from each Serverless project)." >&2
  exit 1
fi

python3 <<'PY' "$O11Y_KIBANA_URL" "$SECURITY_KIBANA_URL" "$NGINX_CONF"
import sys
import urllib.parse
from pathlib import Path


def parse(raw: str) -> tuple[str, int]:
    p = urllib.parse.urlparse(raw.strip())
    if p.scheme not in ("https", "http"):
        sys.stderr.write(f"URL must start with https:// or http://: {raw!r}\n")
        sys.exit(1)
    host = p.hostname or ""
    if not host:
        sys.stderr.write(f"Could not parse host from URL: {raw!r}\n")
        sys.exit(1)
    port = p.port or (443 if p.scheme == "https" else 80)
    return host, port


def server_block(listen: int, host_header: str, proxy_host: str, proxy_port: int) -> str:
    scheme = "https" if proxy_port == 443 else "http"
    # Same policy string as Instruqt service-tab CSP: Elastic CDN + inline styles for Kibana in iframes.
    csp = (
        "script-src 'self' https://kibana.estccdn.com; "
        "worker-src blob: 'self'; "
        "style-src 'unsafe-inline' 'self' https://kibana.estccdn.com; "
        "style-src-elem 'unsafe-inline' 'self' https://kibana.estccdn.com"
    )
    return f"""
server {{
    listen {listen} default_server;
    listen [::]:{listen} default_server;
    server_name _;
    location / {{
        proxy_pass {scheme}://{proxy_host}:{proxy_port}/;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_set_header Host {host_header};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Content-Security-Policy "{csp}";
        proxy_hide_header Content-Security-Policy;
        proxy_hide_header X-Frame-Options;
        add_header Content-Security-Policy "{csp}" always;
        proxy_buffering off;
        proxy_read_timeout 360s;
        proxy_send_timeout 360s;
    }}
}}
"""

o11y_url, sec_url, out = sys.argv[1], sys.argv[2], Path(sys.argv[3])
oh, op = parse(o11y_url)
sh, sp = parse(sec_url)
text = (
    "# Generated by render-kibana-proxy.sh — do not edit by hand.\n"
    + server_block(8080, oh, oh, op)
    + server_block(8081, sh, sh, sp)
)
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(text, encoding="utf-8")
PY

rm -f /etc/nginx/sites-enabled/default
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/elastic-lab-kibana-proxy.conf
nginx -t
if pgrep -x nginx >/dev/null 2>&1; then
  nginx -s reload
else
  nginx
fi

echo "Kibana proxy listening on :8080 (Observability) and :8081 (Security)."
